source "https://rubygems.org"

gem "roda", "~> 3.73"
gem "puma", "~> 6.4"
gem "rackup", "~> 2.1"
gem "sequel", "~> 5.74"
gem "pg", "~> 1.5"
gem "sequel_tools", "~> 0.1.14"
gem "tilt", "~> 2.3"
gem "erubi", "~> 1.12"
gem "forme", "~> 2.4"
gem "dry-initializer", "~> 3.1"
gem "dry-types", "~> 1.5"
gem "dry-inflector", "~> 0.3.0"
gem "zeitwerk", "~> 2.6"
gem "listen", "~> 3.8"
gem "dry-configurable", "~> 0.15.0"
gem "dotenv", "~> 2.8"
gem "concurrent-ruby", "~> 1.2"

gem "rake", "~> 13.1"
